name: CustomItemRegistry
description: Create custom items and recipes, complete with API! Wow!
version: ${project.version}-${git.commit.id.abbrev}
website: http://robomwm.com
author: RoboMWM
main: com.robomwm.customitemregistry.CustomItemRegistry
api-version: '1.18'
commands:
  crecipe:
      usage: /crecipe <shaped/shapeless> <customitem name> - Registers a recipe for a registered custom item. Use shaped if the order (shape of recipe) matters, otherwise use shapeless if only the ingredients matter. Note that recipes only use one item per slot.
      permission: customitemregistry.crecipe
      aliases: [crecipes]
  citem:
      usage: /citem <list/name/register/get/lore>
      permission: customitemregistry.citem
      aliases: [citems]
  cremove:
      usage: /cremove <name> - removes custom item and blocks its recipes. Recipes are fully removed on server restart.
      permission: customitemregistry.cremove
permissions:
    customitemregistry.*:
        description: Grants ALL THE THINGS
        children:
            customitemregistry.citem: true
            customitemregistry.crecipe: true
            customitemregistry.cremove: true
    customitemregistry.citem:
        description: Permission to /citem
        default: op
    customitemregistry.crecipe:
        description: Permission to /crecipe
        default: op
    customitemregistry.cremove:
        description: Permission to /cremove
        default: op
